#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DevQuiz.Android.Resource", IsApplication=true)]

namespace DevQuiz.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backArrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int forwardArrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int AboutBtnBack = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int AboutTvActionBarText = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int DifficultyChooserBtnBack = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int DifficultyChooserBtnEasy = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int DifficultyChooserBtnForward = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int DifficultyChooserBtnMedium = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int DifficultyChooserBtnPro = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int MainBtnAbout = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int MainBtnStart = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int MainTvAppName = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int MainTvBuiltWith = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int MainTvSubheader = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int QuestionAnswerListItemTvAnswerNumber = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int QuestionAnswerListItemTvAnswerText = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int relativeLayout1 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DifficultyChooserView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GameLoopView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GameResultView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int QuestionAnswerListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StartView = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int About = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int AboutTheApp = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int AppName = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int AppNameSubheader = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int Back = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int BuiltWith = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int Choose_difficulty = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int EASY = 2130968588;
			
			// aapt resource value: 0x7f040000
			public const int ErrorTitle = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int Finish = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int Loading = 2130968577;
			
			// aapt resource value: 0x7f04000d
			public const int MEDIUM = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int Next = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int PRO = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int PleaseSelectADifficulty = 2130968591;
			
			// aapt resource value: 0x7f040005
			public const int StartNewGame = 2130968581;
			
			// aapt resource value: 0x7f040010
			public const int Warning = 2130968592;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int actionBarBackButton = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int actionBarNextButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int appActionBar = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
